version: '3.7'
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/:/app
      - node_modules:/app/node_modules
    working_dir: /app
  backend:
    build: ./backend/
    environment:
      MIX_ENV: dev
    env_file:
      - ./backend/dev.env
    ports:
      - 4000:4000
    volumes:
      - ./backend/:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_app_dev
    ports:
      - 5432:5432
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
volumes:
  pgdata:
  node_modules:  
