version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - './frontend:/app'
    depends_on:
      - backend
    network_mode: "host"
  backend:
    container_name: backend
    build:
      context: ./backend
    environment:
      MIX_ENV: dev
    env_file:
      - ./backend/.env
    volumes:
      - './backend:/backend'
    network_mode: "host"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  pgdata:
    driver: local
