version: "3.7"

services:
  database:
    image: postgres
    container_name: backend_dev
    restart: always
    ports: 
      - 54320:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend_dev
    volumes: 
      - pgdata:/data/postgres
      
volumes: 
  pgdata: 
    driver: local