version: '3.1'

services:

  db:
    container_name: benefits_postgres
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: benefits_dev
